### ISSUE TITLE
poll error: Error: Invalid content-type. Expected application/json but received text/plain

### ISSUE THREAD

**Issue by bastervrugt** [gruijter/nl.maikvanwel.youless#2]
Mijn energiemeter is vervangen door een slimme meter, hierdoor kan ik nu de P1 poort gebruiken van youless.
Homey kan mijn "LS110/120 E" device nog steeds uitlezen (power en power meter)
Maar ik wil ook graag mijn gasverbruik monitoren via homey.
Ik kan een "LS120 P1" device toevoegen maar krijg na toevoegen de volgende foutmelding:

`2018-05-01 21:16:04 [err] [ManagerDrivers] [LS120] [0] poll error: Error: Invalid content-type. Expected application/json but received text/plain `

De pagina http://ip.address/a?f=j opvragen geeft wel een json response terug.
 
```
HTTP/1.1 200 OK
Content-Type: application/json
```

Model: LS120
Firmware: 1.4.1-PO

**Comment by gruijter** [comment]
Weird. Do you use the pvOutput service? If not try installing the EL (enelogic) firmware Version in the ls120.

**Comment by bastervrugt** [comment]
That fixed the issue! 
Weird as the only difference in the firmware should be the 3th party upload service.

**Comment by gruijter** [comment]
Yep weird. Anyhow, Im glad it fixed your problem.🤗
