### ISSUE TITLE
Instellingen worden overgschreven met defaults na aanpassen "Max gebruik" in de Homey app.

### ISSUE THREAD

**Issue by CBR1100xx** [gruijter/nl.maikvanwel.youless#3]
Mijn Energiemeter werkt met een schijf, waarde 375 (Analoog).

Wanneer ik het "Max gebruik" voor de ring aanpas in je Youless app dan komt de 
Pulsen/kWh weer op 1000 te staan ipv mijn ingestelde 375.
De Youless Google app geeft meteen foutief lage waarden.
In de webbrowser met ik de waarde weer naar 375 zetten.

(Volgens mij doet hij dat ook bij  S0 imp/kWh:  ) 
[Youless 1000 corrected to 375.pdf](https://github.com/gruijter/nl.maikvanwel.youless/files/2014713/Youless.1000.corrected.to.375.pdf)
[Homey Youless app.pdf](https://github.com/gruijter/nl.maikvanwel.youless/files/2014726/Homey.Youless.app.pdf)

Harald

**Comment by gruijter** [comment]
Is dit in de laatste versie nog steeds zo, of is het ondertussen opgelost?
